### ISSUE TITLE
Create a new API to get all Product

### ISSUE THREAD

**Issue by dlcdev** [MateusMeli/Desafio_Spring#10]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**

 

**Descreva a solução que você gostaria**

**Informações adicionais**

**Checklist**  
- [ ] A issue possui nome significativo.
- [ ] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [ ] A issue possui labels.

**Comment by MateusMeli** [comment]
Resolvida em #12
