### ISSUE TITLE
9 - Controle de estoque

### ISSUE THREAD

**Issue by gucotrim** [MateusMeli/Desafio_Spring#19]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**

Para cada solicitação de compra é necessário realizar o controle de estoque
disponível. Por exemplo: Se forem solicitadas 4 unidades de um produto e houver
apenas duas, coloque as restrições e avisos correspondentes.

**Descreva a solução que você gostaria**

Validar no método de enviar pedido a disponibilidade de estoque, caso a quantidade do pedido exceda a quantidade do estoque, gerar uma exceção. 

**Informações adicionais**

**Checklist**  
- [ ] A issue possui nome significativo.
- [ ] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [ ] A issue possui labels.

**Comment by MateusMeli** [comment]
Resolvido em #21
