### ISSUE TITLE
10 - Carrinho de compras

### ISSUE THREAD

**Issue by gucotrim** [MateusMeli/Desafio_Spring#20]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**

Permite a utilização de um “carrinho de compras” onde para cada pedido de
compra existe um valor total acumulado e devolvido ao utilizador. Por exemplo: Se
um produto de R$ 900 foi enviado em um pedido de compra e outro produto de
R$ 300 foi enviado em outro, devo receber a soma dos dois (R$ 1200) como
resposta.

**Descreva a solução que você gostaria**

Ao realizar o pedido de compra, deve-se calcular o valor total e devolver como resposta um Json similar a um carrinho de compra, conforme descrito no arquivo de Definições Técnicas

**Informações adicionais**

Acredita-se que a definição de "carrinho de compra" do usuário não está muito clara e coerente com a funcionalidade de um carrinho, segure-se que em uma próxima issue seja feito um CRUD para o carrinho, assim, a partir de cada carrinho possa ser gerado um novo pedido de compra.

**Checklist**  
- [ ] A issue possui nome significativo.
- [ ] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [ ] A issue possui labels.

**Comment by MateusMeli** [comment]
Resolvido em #21
